version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
- package-ecosystem: "maven"
  directories: 
  - "/"
  - "agent"
  - "boot"
  - "cli"
  - "common"
  - "dumper"
  - "instrumenter"
  - "it-dist-check"
  - "it-test"
  - "parsers"
  - "plugin"
  - "plugin-generator"
  - "profiler"
  - "runtime"
  - "war-lib"
  - "web"
  schedule:
    interval: "monthly"    
