name: bump version in gradle.properties
description: Updates gradle.properties with the new version
inputs:
  version:
    required: true
    description: new version
  token:
    required: true
    description: token to use when

runs:
  using: composite
  steps:
    - name: Update the worktree
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        ref: ${{ github.ref_name }}
        token: ${{ inputs.token }}
        persist-credentials: true

    - name: update version to ${{ inputs.version }}
      shell: bash
      with:
        VERSION: ${{ inputs.version }}
        REF_NAME: ${{ github.ref_name }}
      # language=bash
      run: |
        # Check if version needs to be updated
        VERSION_LINE="profiler.version=$VERSION"
        if grep -Fqx -- "${VERSION_LINE}" gradle.properties; then
          echo "Version is already up to date"
          exit 0
        fi

        # Update version in gradle.properties
        sed -i "s/^profiler\.version=.*$/${VERSION_LINE}/" gradle.properties

        # Commit and push changes
        git add gradle.properties
        git commit -m "chore: bump version to $VERSION" -m "[ci-skip]"
        git push origin "$REF_NAME"

    - name: Update the worktree, revert to the default token
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        ref: ${{ github.ref_name }}
        token: ${{ github.token }}
        persist-credentials: false
