apiVersion: v2
name: profiler-stack
description: A Helm chart for profiler-stack

# A chart can be either an 'application' or a 'library' chart.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.1.0

home: https://github.com/Netcracker/qubership-profiler-agent/
maintainers:
  - name: NetCracker
    email: opensourcegroup@netcracker.com

dependencies:
  - name: collector
    version: ~0
    repository: https://github.com/Netcracker/qubership-profiler-agent/
    condition: collector.install
  - name: compactor
    version: ~0
    repository: https://github.com/Netcracker/qubership-profiler-agent/
    condition: compactor.install
  - name: dumps-collector
    version: ~0
    repository: https://github.com/Netcracker/qubership-profiler-agent/
    condition: dumps-collector.install
  - name: maintenance
    version: ~0
    repository: https://github.com/Netcracker/qubership-profiler-agent/
    condition: maintenance.install
  - name: migration
    version: ~0
    repository: https://github.com/Netcracker/qubership-profiler-agent/
    condition: migration.install
  - name: query
    version: ~0
    repository: https://github.com/Netcracker/qubership-profiler-agent/
    condition: query.install
