{
 "title": "CDT Load Generator",
 "description": "Visualize k6 OSS results stored in Prometheus",
 "tags": [
  "prometheus",
  "k6"
 ],
 "time": { "from": "2025-04-09T10:07:34.000Z", "to": "2025-04-09T10:20:02.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "quantile_stat", "label": "Trend Metrics Query", "query": { "query": "metrics(k6_http_req_duration_)" } },
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values({namespace=\"$namespace\"},pod)"
    }
   },
   { "name": "interval", "query": "20s" }
  ]
 },
 "panels": [
  {
   "title": "Quick facts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "description": "Shows time from VM start",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{namespace=\"$namespace\", pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "stat",
     "description": "Shows resident memory",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "stat",
     "description": "Shows total routines count in selected area",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "sum(go_goroutines{namespace=\"$namespace\", pod=\"$pod\"})"
      }
     ]
    },
    {
     "title": "Open FDs",
     "type": "stat",
     "description": "Shows amount of currently opened file descriptors",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "process_open_fds{namespace=\"$namespace\", pod=\"$pod\"}"
      }
     ]
    },
    {
     "title": "Performance Overview",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 10, "x": 14, "y": 1 },
     "targets": [
      {
       "expr": "sum(k6_vus{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Virtual Users"
      },
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "HTTP requests duration ($quantile_stat)"
      },
      {
       "expr": "sum(irate(k6_http_reqs_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "HTTP requests rate"
      },
      {
       "expr": "avg(round(k6_http_req_failed_rate{namespace=~\"$namespace\", pod=~\"$pod\"}, 0.1)*100)",
       "legendFormat": "HTTP request failure rate"
      }
     ]
    },
    {
     "title": "Checks list",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 129 },
     "targets": [
      {
       "expr": "round(k6_checks_rate{namespace=~\"$namespace\", pod=~\"$pod\"}, 0.1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Checks Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 129 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "round(k6_checks_rate{namespace=~\"$namespace\", pod=~\"$pod\"}, 0.1)*100",
       "legendFormat": "{{check}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Request Duration",
     "type": "stat",
     "description": "Select a different Stat to change the query",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "k6_http_req_duration_$quantile_stat{group=\"::files. thread dump\", namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "Thread Dumps"
      },
      {
       "expr": "k6_http_req_duration_$quantile_stat{group=\"::files. top dump\", namespace=~\"$namespace\", pod=~\"$pod\"}",
       "legendFormat": "Top Dumps"
      }
     ]
    },
    {
     "title": "Iterations",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(k6_iteration_duration_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Iteration Duration ($quantile_stat)"
      },
      {
       "expr": "avg(k6_dropped_iterations_total{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Dropped Iterations"
      }
     ]
    },
    {
     "title": "Transfer Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(irate(k6_data_sent_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Data Sent"
      },
      {
       "expr": "avg(irate(k6_data_received_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "Data Received"
      }
     ]
    },
    {
     "title": "HTTP request failures",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(sum(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"})) or (0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 3, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(k6_http_reqs_total{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CDT Load Generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CDT Read Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k6_cdt_read_count_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CDT Send Time ($quantile_stat)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 21, "x": 3, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "k6_cdt_send_time_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\", group=\"::tcp. flush\"}",
       "legendFormat": "TCP: Flush"
      },
      {
       "expr": "k6_cdt_send_time_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\", group=\"::tcp. init connect\"}",
       "legendFormat": "TCP: Init Connect"
      },
      {
       "expr": "k6_cdt_send_time_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\", group=\"::tcp. send calls\"}",
       "legendFormat": "TCP: Send Calls"
      },
      {
       "expr": "k6_cdt_send_time_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\", group=\"::tcp. send meta\"}",
       "legendFormat": "TCP: Send Meta"
      }
     ]
    },
    {
     "title": "CDT Send Count",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k6_cdt_send_count_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__range])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Latency Timings ($quantile_stat)",
     "type": "timeseries",
     "description": "Select a different Stat to change the query\n\n<a href=\"https://k6.io/docs/using-k6/metrics/reference/#http\" target=\"_blank\">HTTP-specific built-in metrics</a>",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(k6_http_req_blocked_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Request Blocked Time"
      },
      {
       "expr": "avg(k6_http_req_sending_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Request Sending Time"
      },
      {
       "expr": "avg(k6_http_req_waiting_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Time to First Byte"
      },
      {
       "expr": "avg(k6_http_req_receiving_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Response Receiving Time"
      },
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "Total Request Duration"
      }
     ]
    },
    {
     "title": "HTTP Latency Stats ($quantile_stat)",
     "type": "timeseries",
     "description": "Select a different Stat to change the query",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "HTTP requests duration"
      },
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\", expected_response=\"true\"})",
       "legendFormat": "Succeeded HTTP requests duration"
      },
      {
       "expr": "avg(k6_http_req_duration_$quantile_stat{namespace=~\"$namespace\", pod=~\"$pod\", expected_response=\"false\"})",
       "legendFormat": "Failed HTTP requests duration"
      }
     ]
    },
    {
     "title": "HTTP Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(k6_http_reqs_total{namespace=~\"$namespace\", pod=~\"$pod\"}[$__rate_interval]))",
       "legendFormat": "HTTP requests rate"
      },
      {
       "expr": "sum(irate(k6_http_reqs_total{namespace=~\"$namespace\", pod=~\"$pod\", expected_response=\"false\"}[$__rate_interval]))",
       "legendFormat": "HTTP failed requests rate"
      },
      {
       "expr": "sum(irate(k6_http_reqs_total{namespace=~\"$namespace\", pod=~\"$pod\", expected_response=\"true\"}[$__rate_interval]))",
       "legendFormat": "HTTP succeeded requests rate"
      }
     ]
    },
    {
     "title": "Requests by URL",
     "type": "table",
     "description": "min/max/p95/p99 depends on the available Quantile Stats",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "avg by(name, method, status) (k6_http_req_duration_min{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "min"
      },
      {
       "expr": "avg by(name, method, status) (k6_http_req_duration_max{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "max"
      },
      {
       "expr": "avg by(name, method, status) (k6_http_req_duration_p95{namespace=~\"$namespace\", pod=~\"$pod\"})",
       "legendFormat": "p95"
      },
      {
       "expr": "avg by(name, method, status) (k6_http_req_duration_p99{namespace=~\"$namespace\", pod=~\"$pod\"}) or (\"Not used\")",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "GO: Memory and GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Process memory",
   "type": "timeseries",
   "description": "Shows resident and virtual memory volume",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Virtual"
    }
   ]
  },
  {
   "title": "Process memory / second",
   "type": "timeseries",
   "description": "Shows per-second memory rate",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}[2m])",
     "legendFormat": "Resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{namespace=\"$namespace\", pod=\"$pod\"}[2m])",
     "legendFormat": "Virtual"
    }
   ]
  },
  {
   "title": "Go memstats",
   "type": "timeseries",
   "description": "Shows how much Go is using from the amount of memory the Prometheus process is using from the kernel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Bytes Allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[2m])",
     "legendFormat": "Alloc Rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Stack Inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Heap Inuse"
    }
   ]
  },
  {
   "title": "Go memstats / second",
   "type": "timeseries",
   "description": "Shows per-second rate of how much Go is using from the amount of memory the Prometheus process is using from the kernel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{namespace=\"$namespace\", pod=\"$pod\"}[2m])",
     "legendFormat": "Bytes Allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=\"$namespace\", pod=\"$pod\"}[2m])",
     "legendFormat": "Alloc Rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=\"$namespace\", pod=\"$pod\"}[2m])",
     "legendFormat": "Stack Inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=\"$namespace\", pod=\"$pod\"}[2m])",
     "legendFormat": "Heap Inuse"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Shows the number of goroutined that currently exists",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "timeseries",
   "description": "Shows  the summary of the GC invocation durations",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "Open fds",
   "type": "timeseries",
   "description": "Shows the current number of used file descriptors",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "Open fds"
    }
   ]
  },
  {
   "title": "Open / closed fds delta",
   "type": "timeseries",
   "description": "Shows delta of used file descriptors. A positive value shows newly opened descriptors, a negative value shows closed descriptors.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(process_open_fds{namespace=\"$namespace\", pod=\"$pod\"}[2m])",
     "legendFormat": "Open / closed fds delta"
    }
   ]
  }
 ]
}