{{- if .Values.compactor.pvc.install }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.compactor.pvc.name }}
  labels:
    {{- include "common.namedLabels" .Values.compactor.pvc | nindent 4 }}
    {{- include "common.commonLabels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.compactor.pvc.annotations | nindent 4 }}
spec:
  {{- $spec := deepCopy .Values.compactor.pvc.spec }}
  {{- if and (ne (.Values.STORAGE_RWX_CLASS | toString) "<nil>") .Values.global.cloudIntegrationEnabled }}
    {{- $_ := set $spec "storageClassName" .Values.STORAGE_RWX_CLASS }}
  {{- end }}
  {{- toYaml $spec | nindent 2 }}
{{- end }}
