name: Dependency Submission

# See https://github.com/gradle/actions/blob/768a17f3488dc3fe0155ff431553e1f53d57e22e/dependency-submission/README.md#the-dependency-submission-action
# The action allows GitHub to alert about reported vulnerabilities in the project
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-submission:
    name: Submit dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Set up JDK 17
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: zulu
        java-version: 17
        server-id: central
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4
      with:
        # Profiler plugins do not expose the dependencies to the runtime, so the versions used for the build
        # do not affect the execution. At the same time, we might need to build plugins for different thirdparty
        # versions, so we intentionally exclude :plugins:* projects from the submitted dependencies
        dependency-graph-exclude-projects: |
          :plugins:.*
