name: Dependency Submission

# See https://github.com/gradle/actions/blob/768a17f3488dc3fe0155ff431553e1f53d57e22e/dependency-submission/README.md#the-dependency-submission-action
# The action allows GitHub to alert about reported vulnerabilities in the project
on:
  push:
    branches:
      - main

# Declare default permissions as read-only.
permissions: read-all

jobs:
  dependency-submission:
    name: Submit dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout sources
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with:
        persist-credentials: false
    - name: Set up JDK 21
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        distribution: zulu
        java-version: 21
        server-id: central
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@ed408507eac070d1f99cc633dbcf757c94c7933a # v4
      with:
        # Profiler plugins do not expose the dependencies to the runtime, so the versions used for the build
        # do not affect the execution. At the same time, we might need to build plugins for different thirdparty
        # versions, so we intentionally exclude :plugins:* projects from the submitted dependencies
        dependency-graph-exclude-projects: |
          :plugins:.*
