name: Release

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      version:
        required: true
        default: ''
        type: string
        description: new version number, without leading v
      branch_name:
        required: true
        default: 'main'
        description: branch name that should be released

jobs:
  release-to-central:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create git tag
        uses: actions/github-script@v7
        with:
          # language=javascript
          script: |
            try {
              const tagName = 'v1.0.0'; //`v${context.payload.inputs.version}`;
              const branchName = 'main'; // context.payload.inputs.branch_name;

              // Check if tag exists
              try {
                const { data: ref } = await github.rest.git.getRef({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  ref: `tags/${tagName}`
                });
                core.setFailed(`Tag ${tagName} already exists, and it points to ${ref.object.sha}, ${ref.object.url}`);
                return;
              } catch (e) {
                if (e.status !== 404) {
                    core.setFailed(`Can't get information for tag ${tagName}: ${e.message}`);
                }
              }

              // Get the latest commit SHA from the branch
              const { data: ref } = await github.rest.git.getRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `heads/${branchName}`
              });

              // Create tag
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${tagName}`,
                sha: ref.object.sha
              });

              console.log(`Created tag ${tagName} on branch ${branchName} at ${ref.object.sha}, ${ref.object.url}`);
            } catch (error) {
              core.setFailed(`Failed to create tag: ${error.message}`);
            }

      # TODO: publish GitHub release (automatic? manual?)

      - name: Publish to Central Portal
        if: false
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: publishAggregationToCentralPortal
          properties: |
            release=true
            centralPortalPublishingType=USER_MANAGED
        env:
          CENTRAL_PORTAL_USERNAME: ${{ secrets.MAVEN_USER }}
          CENTRAL_PORTAL_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          SIGNING_PGP_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          SIGNING_PGP_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
