# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/super-linter/super-linter
# Configuration file for super-linter example:
# .github/super-linter.env
# Configuration files for individual linters should be placed in .github/linters

name: Lint Code Base

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      full_scan:
        type: boolean
        default: false
        required: false
        description: "Lint all codebase"
permissions:
  contents: read

jobs:
  run-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: "Get the common linters configuration"
        uses: actions/checkout@v4
        with:
          ref: main # fix/superlinter-config
          repository: netcracker/.github
          path: netcracker.github/
          sparse-checkout: |
            config/linters

      - name: "Apply the common linters configuration"
        run: |
          ls -l netcracker.github/config/linters
          mkdir -p .github/linters
          cp --update=none -vR netcracker.github/config/linters/ .github/
          rm -rf netcracker.github/

      - name: "Load super-linter environment file"
        shell: bash
        # language=bash
        run: |
          # The grep is need here because GitHub Actions will not accept comments.
          # We need to skip blank lines as GitHub Actions might fail to process them as well
          cat .github/linters/super-linter.env .github/super-linter.env | grep -v '^#' | grep -vE '^\s*$' >> "$GITHUB_ENV" || true

      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v7.3.0
        env:
          VALIDATE_ALL_CODEBASE: ${{ inputs.full_scan || false }}
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: ${{ github.event.pull_request.base.ref }}
